"""
goal_conditioned_agent.py
=========================
Tabular goal-conditioned Q-learning agent with Hindsight Experience Replay.

Based on the approach in:
    "A Single Goal is All You Need: On the Elegance of Task-Conditioned RL"
    (Mezghani et al., 2023)

Key ideas
---------
* The Q-function is conditioned on both state *and* goal:
  Q(s, g, a) — the value of taking action a from state s when the
  desired goal is g.
* **Hindsight Experience Replay (HER)** (Andrychowicz et al., 2017) is
  applied after each episode: for every transition (s, a, r, s') in the
  episode, k additional "virtual" transitions are generated by substituting
  a future achieved state as the relabeled goal.  This gives a dense
  learning signal even when the originally intended goal was never reached.
* Reward function: sparse binary — +1.0 when next_state == goal, else 0.
* Policy: ε-greedy over Q(s, g, ·).

Usage (tabular GridWorld)
-------------------------
    agent = GoalConditionedAgent(
        n_states=25, n_actions=4, gamma=0.99,
        alpha=0.1, epsilon=1.0, seed=42,
    )
    goal = 24  # bottom-right corner
    agent.set_goal(goal)
    obs, _ = env.reset()
    while not done:
        action = agent.select_action(obs)
        next_obs, _, terminated, truncated, info = env.step(action)
        agent.update(obs, action, 0.0, next_obs, terminated, truncated, info)
        obs = next_obs
    agent.finish_episode_with_her()
"""

from __future__ import annotations

from typing import Any

import numpy as np

from agents.base_agent import BaseAgent


class GoalConditionedAgent(BaseAgent):
    """Tabular goal-conditioned Q-learning agent with Hindsight Experience Replay.

    Parameters
    ----------
    n_states :
        Total number of discrete states |S|.
    n_actions :
        Number of discrete actions |A|.
    gamma :
        Discount factor γ ∈ [0, 1).
    alpha :
        Q-learning step size α.
    epsilon :
        Initial ε for ε-greedy exploration.
    epsilon_min :
        Minimum ε after annealing.
    epsilon_decay :
        Multiplicative decay applied to ε after each episode.
    her_k :
        Number of HER goal substitutions per real transition.
        ``her_k=4`` is the default from the original HER paper.
    seed :
        Random seed.
    """

    def __init__(
        self,
        n_states: int,
        n_actions: int,
        gamma: float = 0.99,
        alpha: float = 0.1,
        epsilon: float = 1.0,
        epsilon_min: float = 0.05,
        epsilon_decay: float = 0.995,
        her_k: int = 4,
        seed: int | None = None,
    ) -> None:
        super().__init__(n_actions=n_actions, gamma=gamma, seed=seed)
        self.n_states = n_states
        self.alpha = alpha
        self.epsilon = epsilon
        self.epsilon_min = epsilon_min
        self.epsilon_decay = epsilon_decay
        self.her_k = her_k

        # Q-table: shape (n_states, n_goals=n_states, n_actions)
        self.Q = np.zeros((n_states, n_states, n_actions), dtype=np.float64)

        # Per-episode transition buffer used for HER relabeling
        self._episode_buffer: list[tuple[int, int, float, int, bool]] = []
        self._current_goal: int = 0

    # ------------------------------------------------------------------
    # Goal management
    # ------------------------------------------------------------------

    def set_goal(self, goal: int) -> None:
        """Set the current goal state before an episode starts.

        Parameters
        ----------
        goal :
            Flat state index of the desired goal.
        """
        self._current_goal = int(goal)
        self._episode_buffer = []

    # ------------------------------------------------------------------
    # BaseAgent interface
    # ------------------------------------------------------------------

    def select_action(self, observation: Any) -> int:
        """ε-greedy action selection conditioned on the current goal.

        Parameters
        ----------
        observation :
            Array-like containing the flat state index at position 0.
        """
        self._increment_step()
        state = int(np.asarray(observation).flat[0])

        if self.np_random.random() < self.epsilon:
            return int(self.np_random.integers(0, self.n_actions))

        return int(np.argmax(self.Q[state, self._current_goal]))

    def update(
        self,
        observation: Any,
        action: Any,
        reward: float,
        next_observation: Any,
        terminated: bool,
        truncated: bool,
        info: dict,
    ) -> dict:
        """One-step Q-learning update for the real (s, g, a, r, s') transition.

        Also stores the transition for post-episode HER relabeling.

        Returns
        -------
        metrics : dict
            ``{"td_error": float, "q_value": float}``
        """
        state = int(np.asarray(observation).flat[0])
        next_state = int(np.asarray(next_observation).flat[0])
        a = int(action)
        g = self._current_goal

        # Sparse goal-reaching reward overrides environment reward
        goal_reward = 1.0 if next_state == g else 0.0
        goal_terminated = next_state == g

        td_target = (
            goal_reward
            if goal_terminated
            else goal_reward + self.gamma * float(np.max(self.Q[next_state, g]))
        )
        td_error = td_target - self.Q[state, g, a]
        self.Q[state, g, a] += self.alpha * td_error

        # Store raw transition (no goal, no reward — we relabel later in HER)
        self._episode_buffer.append((state, a, 0.0, next_state, bool(terminated or truncated)))

        return {"td_error": float(td_error), "q_value": float(self.Q[state, g, a])}

    def reset(self) -> None:
        """Called at the start of each episode — clears the episode buffer."""
        super().reset()
        self._episode_buffer = []

    # ------------------------------------------------------------------
    # Hindsight Experience Replay (HER)
    # ------------------------------------------------------------------

    def finish_episode_with_her(self) -> None:
        """Apply HER relabeling after an episode ends.

        For each transition t in the episode, sample ``her_k`` future
        achieved states from the same episode as substitute goals and
        perform a Q-learning update for each virtual (s, g', a, r', s')
        tuple.  This generates dense learning signal for all pairs of
        (state, future_state) even when the intended goal was never reached.

        Also decays ε by ``epsilon_decay``.
        """
        n = len(self._episode_buffer)
        if n == 0:
            return

        for t, (state, action, _, next_state, _) in enumerate(self._episode_buffer):
            # Future-strategy HER: goals are sampled from steps t..n-1
            future_start = t  # include current step so at least one choice
            future_range = n - future_start
            k = min(self.her_k, future_range)

            chosen = self.np_random.choice(
                np.arange(future_start, n), size=k, replace=False
            )

            for idx in chosen:
                # The achieved "next_state" at the future step becomes the goal
                _, _, _, future_next_state, _ = self._episode_buffer[idx]
                g_her = future_next_state

                her_reward = 1.0 if next_state == g_her else 0.0
                her_terminated = next_state == g_her

                if her_terminated:
                    td_target = her_reward
                else:
                    td_target = her_reward + self.gamma * float(
                        np.max(self.Q[next_state, g_her])
                    )

                td_error = td_target - self.Q[state, g_her, action]
                self.Q[state, g_her, action] += self.alpha * td_error

        # Anneal ε at the end of each episode
        self.epsilon = max(self.epsilon_min, self.epsilon * self.epsilon_decay)
        self._episode_buffer = []

    # ------------------------------------------------------------------
    # Repr
    # ------------------------------------------------------------------

    def __repr__(self) -> str:
        return (
            f"GoalConditionedAgent("
            f"n_states={self.n_states}, n_actions={self.n_actions}, "
            f"alpha={self.alpha}, epsilon={self.epsilon:.3f}, "
            f"her_k={self.her_k})"
        )
